set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'Valloric/YouCompleteMe'

call vundle#end()

" we need to install => :PluginInstall

filetype plugin indent on
syntax on

set nospell
set showcmd
set modeline

set mouse=a

set smarttab
set autoindent smartindent
set tabstop=4
set shiftwidth=4
set expandtab

set runtimepath^=~/.vim/bundle/ctrlp.vim

map <C-n> :NERDTreeToggle<CR>

filetype on
